# Generated by Django 4.2.20 on 2025-04-10 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api_education", "0007_remove_userprogress_completed_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lesson",
            name="content",
        ),
        migrations.CreateModel(
            name="LessonContentBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField()),
                ("block_type", models.CharField(max_length=50)),
                ("data", models.JSONField()),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_blocks",
                        to="api_education.lesson",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
